package com.server.hkj.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HkjMaterialImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjMaterialImageAllPropertiesEquals(HkjMaterialImage expected, HkjMaterialImage actual) {
        assertHkjMaterialImageAutoGeneratedPropertiesEquals(expected, actual);
        assertHkjMaterialImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjMaterialImageAllUpdatablePropertiesEquals(HkjMaterialImage expected, HkjMaterialImage actual) {
        assertHkjMaterialImageUpdatableFieldsEquals(expected, actual);
        assertHkjMaterialImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjMaterialImageAutoGeneratedPropertiesEquals(HkjMaterialImage expected, HkjMaterialImage actual) {
        assertThat(expected)
            .as("Verify HkjMaterialImage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjMaterialImageUpdatableFieldsEquals(HkjMaterialImage expected, HkjMaterialImage actual) {
        assertThat(expected)
            .as("Verify HkjMaterialImage relevant properties")
            .satisfies(e -> assertThat(e.getUrl()).as("check url").isEqualTo(actual.getUrl()))
            .satisfies(e -> assertThat(e.getIsDeleted()).as("check isDeleted").isEqualTo(actual.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjMaterialImageUpdatableRelationshipsEquals(HkjMaterialImage expected, HkjMaterialImage actual) {
        assertThat(expected)
            .as("Verify HkjMaterialImage relationships")
            .satisfies(e -> assertThat(e.getHkjMaterial()).as("check hkjMaterial").isEqualTo(actual.getHkjMaterial()));
    }
}
