package com.server.hkj.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HkjTempImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTempImageAllPropertiesEquals(HkjTempImage expected, HkjTempImage actual) {
        assertHkjTempImageAutoGeneratedPropertiesEquals(expected, actual);
        assertHkjTempImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTempImageAllUpdatablePropertiesEquals(HkjTempImage expected, HkjTempImage actual) {
        assertHkjTempImageUpdatableFieldsEquals(expected, actual);
        assertHkjTempImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTempImageAutoGeneratedPropertiesEquals(HkjTempImage expected, HkjTempImage actual) {
        assertThat(expected)
            .as("Verify HkjTempImage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTempImageUpdatableFieldsEquals(HkjTempImage expected, HkjTempImage actual) {
        assertThat(expected)
            .as("Verify HkjTempImage relevant properties")
            .satisfies(e -> assertThat(e.getUrl()).as("check url").isEqualTo(actual.getUrl()))
            .satisfies(e -> assertThat(e.getIsUsed()).as("check isUsed").isEqualTo(actual.getIsUsed()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTempImageUpdatableRelationshipsEquals(HkjTempImage expected, HkjTempImage actual) {}
}
