package com.server.hkj.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HkjTrackSearchImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTrackSearchImageAllPropertiesEquals(HkjTrackSearchImage expected, HkjTrackSearchImage actual) {
        assertHkjTrackSearchImageAutoGeneratedPropertiesEquals(expected, actual);
        assertHkjTrackSearchImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTrackSearchImageAllUpdatablePropertiesEquals(HkjTrackSearchImage expected, HkjTrackSearchImage actual) {
        assertHkjTrackSearchImageUpdatableFieldsEquals(expected, actual);
        assertHkjTrackSearchImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTrackSearchImageAutoGeneratedPropertiesEquals(HkjTrackSearchImage expected, HkjTrackSearchImage actual) {
        assertThat(expected)
            .as("Verify HkjTrackSearchImage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTrackSearchImageUpdatableFieldsEquals(HkjTrackSearchImage expected, HkjTrackSearchImage actual) {
        assertThat(expected)
            .as("Verify HkjTrackSearchImage relevant properties")
            .satisfies(e -> assertThat(e.getSearchOrder()).as("check searchOrder").isEqualTo(actual.getSearchOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTrackSearchImageUpdatableRelationshipsEquals(HkjTrackSearchImage expected, HkjTrackSearchImage actual) {
        assertThat(expected)
            .as("Verify HkjTrackSearchImage relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getJewelry()).as("check jewelry").isEqualTo(actual.getJewelry()));
    }
}
