package com.server.hkj.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HkjTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTemplateAllPropertiesEquals(HkjTemplate expected, HkjTemplate actual) {
        assertHkjTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertHkjTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTemplateAllUpdatablePropertiesEquals(HkjTemplate expected, HkjTemplate actual) {
        assertHkjTemplateUpdatableFieldsEquals(expected, actual);
        assertHkjTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTemplateAutoGeneratedPropertiesEquals(HkjTemplate expected, HkjTemplate actual) {
        assertThat(expected)
            .as("Verify HkjTemplate auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTemplateUpdatableFieldsEquals(HkjTemplate expected, HkjTemplate actual) {
        assertThat(expected)
            .as("Verify HkjTemplate relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getIsDeleted()).as("check isDeleted").isEqualTo(actual.getIsDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHkjTemplateUpdatableRelationshipsEquals(HkjTemplate expected, HkjTemplate actual) {
        assertThat(expected)
            .as("Verify HkjTemplate relationships")
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()));
    }
}
