# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: server
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: 'start-dev --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB=postgres
      #add your supabase credentials
      - KC_DB_URL=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.idjqfqnlknncdwemqlnf&password=GTeXmTaNk1jeeOyi&prepareThreshold=0
      - KC_DB_USERNAME=postgres.idjqfqnlknncdwemqlnf
      - KC_DB_PASSWORD=GTeXmTaNk1jeeOyi
      #
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      retries: 40
      start_period: 10s
